// Server functions that run real AI-assisted media analysis via Lovable AI Gateway.
// Two-pass approach: forensic analysis + reviewer pass to reduce false "authentic"
// verdicts on AI-generated media. Uses strong reasoning models and conservative
// score normalization.

import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { generateText } from "ai";
import { z } from "zod";
import { createLovableAiGatewayProvider } from "./ai-gateway.server";
import {
  DetectionAnalysisSchema,
  classifyRisk,
  type DetectionAnalysis,
} from "./detection-types";

const JSON_SHAPE = `{
  "prediction": "Authentic" | "Suspicious" | "Fake",
  "authenticity_score": number (0-100),
  "manipulation_score": number (0-100),
  "confidence_score": number (0-100),
  "risk_level": "Low" | "Medium" | "High",
  "explanation": string (20-2000 chars, 2-4 sentences),
  "findings": [ { "category": string, "detail": string, "severity": "low" | "medium" | "high" } ]
}`;

const SYSTEM_PROMPT = `You are DeepGuard AI, a strict forensic analyst specialised in detecting AI-generated and manipulated media. Your job is to decide whether the media is:
(A) CAMERA-AUTHENTIC — captured by a real camera/microphone of a real scene, unedited.
(B) AI-GENERATED / SYNTHETIC — produced or substantially generated by a generative model (Stable Diffusion, Midjourney, DALL·E, Sora, ElevenLabs, voice cloning, GAN faces, etc.).
(C) MANIPULATED — real media that was edited, face-swapped, lip-synced, deepfaked, or partially synthesised.
(D) UNCERTAIN — you cannot tell with confidence.

CRITICAL RULES:
- "No obvious artifacts" is NOT proof of authenticity. Modern generators produce clean output. If the media looks "too perfect", overly coherent, has flawless skin/symmetry, smoothed micro-textures, suspiciously consistent lighting, plastic-looking surfaces, painterly rendering, or composition that looks AI-curated — treat that as a signal of synthesis, not authenticity.
- Be skeptical by default. Lean toward "Suspicious" instead of "Authentic" when in doubt.
- Only return "Authentic" if you can point to concrete camera-authentic evidence (sensor noise, natural imperfections, realistic depth-of-field, plausible imperfect details).

SIGNALS TO CHECK (media-type appropriate):
- Image: hands/fingers/teeth/eyes/ears anomalies, asymmetric jewellery/accessories, melted or garbled text, repeating textures, hair-edge artifacts, impossible reflections/shadows, GAN/diffusion fingerprints, overly smooth skin, unnaturally clean backgrounds, AI-style composition.
- Video: temporal inconsistency, face-boundary flicker, unnatural blinking, lip-sync drift, warped backgrounds across frames, identity drift, frame-to-frame texture instability.
- Audio: cloned voice prosody, flat or robotic cadence, missing breath/lip noises, unnatural noise floor, spectral repetition, mismatched room acoustics, vocoder/TTS artifacts.

SCORING:
- manipulation_score: 0 = certainly authentic, 100 = certainly AI-generated / fake.
- authenticity_score ≈ 100 - manipulation_score.
- confidence_score: how sure you are of YOUR verdict (not how authentic the media is). Low confidence (< 60) means uncertain.
- Risk: 0-30 = Low, 31-60 = Medium, 61-100 = High.
- Prediction: manipulation < 30 = "Authentic", 30-65 = "Suspicious", > 65 = "Fake".
- If you are uncertain (confidence < 60), DO NOT return "Authentic" — return "Suspicious" with manipulation_score in 35-60.

OUTPUT RULES:
- Reply with ONLY a single valid JSON object. No prose, no markdown, no code fences.
- Shape:
${JSON_SHAPE}
- Include 3 to 6 concrete findings. Each cites a specific observation.
- Keep "explanation" 40-800 chars.`;

const REVIEWER_PROMPT = `You are a senior forensic reviewer auditing another analyst's deepfake/AI-generation verdict on a piece of media. The media is attached again for you to re-examine independently.

The previous analyst's verdict (JSON) is provided. Your task:
1. Re-examine the media yourself with fresh eyes.
2. Decide if the previous verdict is too lenient (called something authentic that is actually AI-generated or manipulated).
3. Modern AI generators produce clean output — "looks normal" does NOT mean authentic.
4. If you spot ANY signs of synthesis the previous analyst missed (hand/finger/eye/text/texture/lighting/composition anomalies for images; temporal/lip-sync issues for video; prosody/cadence issues for audio), raise the verdict.
5. If you agree, keep it.

Return ONLY a single JSON object matching the same shape as the previous verdict:
${JSON_SHAPE}

Be conservative: when in genuine doubt about authenticity, prefer "Suspicious" over "Authentic".`;

function extractJson(raw: string): unknown {
  let s = raw.trim();
  s = s.replace(/```json\s*/gi, "").replace(/```\s*/g, "").trim();
  const start = s.indexOf("{");
  const end = s.lastIndexOf("}");
  if (start === -1 || end === -1 || end <= start) {
    throw new Error("AI returned no JSON object");
  }
  s = s.slice(start, end + 1);
  try {
    return JSON.parse(s);
  } catch {
    const cleaned = s
      .replace(/,\s*}/g, "}")
      .replace(/,\s*]/g, "]")
      // eslint-disable-next-line no-control-regex
      .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g, "");
    return JSON.parse(cleaned);
  }
}

const ImageInput = z.object({
  imageBase64: z.string().min(10),
  mimeType: z.string(),
  filename: z.string().max(255),
});

const AudioInput = z.object({
  audioBase64: z.string().min(10),
  mimeType: z.string(),
  filename: z.string().max(255),
});

const VideoInput = z.object({
  framesBase64: z.array(z.string().min(10)).min(1).max(12),
  filename: z.string().max(255),
});

type MediaPart =
  | { type: "text"; text: string }
  | { type: "image"; image: string; mimeType?: string }
  | { type: "file"; data: string; mediaType: string };

// Conservative normalization: keeps prediction/score/risk consistent and
// downgrades over-confident "Authentic" verdicts when confidence is low.
function normalize(a: DetectionAnalysis): DetectionAnalysis {
  let manip = Math.max(0, Math.min(100, a.manipulation_score));
  const conf = Math.max(0, Math.min(100, a.confidence_score));

  // Low-confidence "Authentic" → push into Suspicious band.
  if (manip < 30 && conf < 60) {
    manip = Math.max(manip, 40);
  }

  const auth = Math.max(0, Math.min(100, 100 - manip));
  const prediction: DetectionAnalysis["prediction"] =
    manip > 65 ? "Fake" : manip >= 30 ? "Suspicious" : "Authentic";

  return {
    ...a,
    manipulation_score: manip,
    authenticity_score: auth,
    confidence_score: conf,
    prediction,
    risk_level: classifyRisk(manip),
  };
}

async function callModel(
  apiKey: string,
  modelId: string,
  system: string,
  userParts: MediaPart[],
  timeoutMs = 45000,
): Promise<DetectionAnalysis> {
  const gateway = createLovableAiGatewayProvider(apiKey);
  const model = gateway(modelId);

  const result = await Promise.race([
    generateText({
      model,
      system,
      messages: [
        {
          role: "user",
          content: userParts as never,
        },
      ],
      providerOptions: {
        lovable: { max_tokens: 2048, temperature: 0.2 },
      },
    }),
    new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("AI model timed out — please try again")), timeoutMs),
    ),
  ]);



  let parsed: unknown;
  try {
    parsed = extractJson(result.text ?? "");
  } catch (e) {
    const snippet = (result.text ?? "").slice(0, 200);
    throw new Error(
      `AI returned invalid JSON: ${e instanceof Error ? e.message : "parse error"}. Snippet: ${snippet}`,
    );
  }

  const validated = DetectionAnalysisSchema.safeParse(parsed);
  if (!validated.success) {
    throw new Error(
      `AI response failed schema validation: ${validated.error.issues
        .slice(0, 3)
        .map((i) => `${i.path.join(".")}: ${i.message}`)
        .join("; ")}`,
    );
  }
  return validated.data;
}

async function runTwoPass(
  mediaParts: MediaPart[],
  mediaType: "image" | "video" | "audio",
  modelId: string,
): Promise<DetectionAnalysis> {
  const apiKey = process.env.LOVABLE_API_KEY;
  if (!apiKey) throw new Error("AI service not configured. LOVABLE_API_KEY missing.");

  // Pass 1: forensic analysis
  const firstParts: MediaPart[] = [
    {
      type: "text",
      text: `Analyse this ${mediaType} for signs of AI generation, deepfake, or manipulation. Be strict. Return ONLY the JSON object.`,
    },
    ...mediaParts,
  ];
  const first = await callModel(apiKey, modelId, SYSTEM_PROMPT, firstParts);

  // Pass 2: reviewer re-examines the same media with the first verdict.
  let reviewed = first;
  try {
    const reviewerParts: MediaPart[] = [
      {
        type: "text",
        text: `Previous analyst verdict:\n${JSON.stringify(first)}\n\nRe-examine the attached ${mediaType} and return your own JSON verdict.`,
      },
      ...mediaParts,
    ];
    const second = await callModel(apiKey, modelId, REVIEWER_PROMPT, reviewerParts);

    // Conservative merge: take the HIGHER manipulation score, average confidence,
    // prefer reviewer's explanation/findings if it raised the verdict.
    const raisedBy = second.manipulation_score - first.manipulation_score;
    const mergedManip = Math.max(first.manipulation_score, second.manipulation_score);
    const mergedConf = Math.round((first.confidence_score + second.confidence_score) / 2);
    const useSecond = raisedBy > 5;
    reviewed = {
      ...first,
      manipulation_score: mergedManip,
      authenticity_score: 100 - mergedManip,
      confidence_score: mergedConf,
      explanation: useSecond ? second.explanation : first.explanation,
      findings: useSecond ? second.findings : first.findings,
      prediction: first.prediction,
      risk_level: first.risk_level,
    };
  } catch (e) {
    // If reviewer fails, fall back to first-pass result.
    console.warn("Reviewer pass failed, using first-pass result:", e);
  }

  return normalize(reviewed);
}

export const analyzeImage = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => ImageInput.parse(d))
  .handler(async ({ data }) => {
    const started = Date.now();
    const model = "google/gemini-2.5-pro";
    const analysis = await runTwoPass(
      [{ type: "image", image: `data:${data.mimeType};base64,${data.imageBase64}`, mimeType: data.mimeType }],
      "image",
      model,
    );
    return { analysis, processingMs: Date.now() - started, model };
  });

export const analyzeVideo = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => VideoInput.parse(d))
  .handler(async ({ data }) => {
    const started = Date.now();
    const model = "google/gemini-2.5-pro";
    const parts: MediaPart[] = data.framesBase64.map((b64) => ({
      type: "image",
      image: `data:image/jpeg;base64,${b64}`,
      mimeType: "image/jpeg",
    }));
    const analysis = await runTwoPass(
      [
        {
          type: "text",
          text: `${data.framesBase64.length} sampled frames (in temporal order) are attached. Examine temporal consistency, face-boundary stability, blinking, lip-sync, identity drift, and any AI-video tell-tale signs.`,
        },
        ...parts,
      ],
      "video",
      model,
    );
    return { analysis, processingMs: Date.now() - started, model };
  });

export const analyzeAudio = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) => AudioInput.parse(d))
  .handler(async ({ data }) => {
    const started = Date.now();
    const model = "google/gemini-2.5-pro";
    const analysis = await runTwoPass(
      [{ type: "file", data: data.audioBase64, mediaType: data.mimeType }],
      "audio",
      model,
    );
    return { analysis, processingMs: Date.now() - started, model };
  });
